### ISSUE TITLE
Visible list not updated with filter function

### ISSUE THREAD

**Issue by felmatias** [jonatanklosko/md-collection-pagination#3]
I used a filter function within the ng-repeat and the visible list didn't update after the filter. Let's say that I had a list of 15 objects and I filtered one that was on the last page. All the objects were gone and the pagination gave me 2 pages of empty list and the last page with the single object.

Sorry that this time I cannot suggest a correction but it is too much reverse engineer lol.

Here is the simplified version of the code that I've used:

`<md-list-item ng-repeat="object in tc.uiObjectList | filter:tc.objectsFilter">`

`<md-collection-pagination collection="tc.objectList" paginated-collection="tc.uiObjectList" per-page="tc.entitiesPerPage"></md-collection-pagination>`

```
        vm.objectsFilter = function(item) {
            if (item.shortName.search(new RegExp(vm.entitySearch, "i")) >= 0) {
                return true;
            }
            return false;
        };
```

**Comment by jonatanklosko** [comment]
Hey, the piece of code you presented it not supposed to work. The reason is that you filter *the paginated* collection, so that on each page only items matching the RegExp are displayed. The result that you're probably trying to achieve is presented on the [demo](http://codepen.io/jonatanklosko/pen/qRJMeq). Check out the code and let me know if it helps =)

**Comment by felmatias** [comment]
Thanks for the reply. You are correct, it was my mistake.

Best regards!
