### ISSUE TITLE
Error: [$compile:infchng] 10 $onChanges() iterations reached. Aborting!

### ISSUE THREAD

**Issue by tahercoolguy** [jonatanklosko/md-collection-pagination#4]
Getting this error
![error](https://user-images.githubusercontent.com/16507436/26906675-a3d5d6f6-4bf7-11e7-84b0-186f7395b20a.png)
for this code 
![error1](https://user-images.githubusercontent.com/16507436/26906682-ac8dcba0-4bf7-11e7-9f43-b015fa11c996.png)
Can you please help me out

**Comment by jonatanklosko** [comment]
Hey, the error is due to the fact that you set `collection` and `paginated-collection` to the same property. Note that `collection` is not meant to be changed while clicking different pages, it's like a base value that we use to extract items accordingly to the selected page and assign those items to a new array, stored in the property set by `paginated-collection`. See the [demo](http://codepen.io/jonatanklosko/full/qRJMeq) that includes filtering. Please let me know if this helps.

**Comment by tahercoolguy** [comment]
Thanks For Reply
You are right i didn't understand correctly. Now it is not displaying any error but pagination functionality now not working . It is not showing 5 items  per page 
following is the output
![error3](https://user-images.githubusercontent.com/16507436/26935245-1cb4b426-4c74-11e7-94f0-53530b9cbfd8.png)
and following is my html
![error4](https://user-images.githubusercontent.com/16507436/26935387-7d7a3380-4c74-11e7-9a73-4145cae87db9.png)

**Comment by jonatanklosko** [comment]
You have to iterate `MasterI` instead of `Master` when using `ng-repeat` (as `MasterI` is the paginated collection). Also note that filtering should be done in a bit different way then and is presented [on the demo I've already linked](https://codepen.io/jonatanklosko/full/qRJMeq).

**Comment by tahercoolguy** [comment]
Opps Sorry my Mistake again .. thanks done 
best Regards..
